apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /app1(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: aspnetapp-app1-service
            port:
              number: 80
      - path: /app2(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: aspnetapp-app2-service
            port:
              number: 80
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: app1
            port:
              number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetapp-app1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aspnetapp-app1
  template: 
    metadata:
      name: aspnetapp-app1-pod
      labels:
        app: aspnetapp-app1       
    spec:
      containers:
        - name: aspnetapp-app1-container
          image: bblacrrepo4321.azurecr.io/brillkuo/demo
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetapp-app1-service
  labels: 
    app: aspnetapp-app1
spec:
  type: ClusterIP 
  selector:
    app: aspnetapp-app1
  ports: 
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetapp-app2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aspnetapp-app2
  template: 
    metadata:
      name: aspnetapp-app2-pod
      labels:
        app: aspnetapp-app2       
    spec:
      containers:
        - name: aspnetapp-app2-container
          image: bblacrrepo4321.azurecr.io/brillkuo/demo
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetapp-app2-service
  labels: 
    app: aspnetapp-app2
spec:
  type: ClusterIP 
  selector:
    app: aspnetapp-app2
  ports: 
    - port: 80
      targetPort: 80
