apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: /
    appgw.ingress.kubernetes.io/health-probe-hostname: localhost
    appgw.ingress.kubernetes.io/health-probe-path: /health
    appgw.ingress.kubernetes.io/health-probe-port: '8085'
    appgw.ingress.kubernetes.io/use-private-ip: 'false'
spec:
  rules:
  - http:
      paths:
      - path: /app1/*
        pathType: Prefix
        backend:
          service:
            name: aspnetapp-app1-service
            port:
              number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetapp-app1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnetapp-app1
  template: 
    metadata:
      name: aspnetapp-app1-pod
      labels:
        app: aspnetapp-app1       
    spec:
      containers:
        - name: aspnetapp-app1-container
          image: bblacrrepo4321.azurecr.io/brillkuo/demo
          ports:
            - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetapp-app1-service
  labels: 
    app: aspnetapp-app1
spec:
  type: ClusterIP 
  selector:
    app: aspnetapp-app1
  ports: 
    - port: 80
      targetPort: 8085
